server:
  port: 8087
spring:
  cloud:
    zookeeper:
     discovery:
         root: /zk-service
     dependencies:
      has-zk-app1:
        path: /has-zk-app
        loadBalancerType: ROUND_ROBIN
        contentTypeTemplate: application/vnd.newsletter.$version+json
        version: v1
       #headers:
        # header1:
        #    - value1
        #  header2:
        #     - value2
        required: false
      # stubs: org.springframework:foo:stubs
     
logging:
  level:
    org.springframework: error