server:
  port: 8087
spring:
  application:
    name: zookeeper-self
  cloud:
    zookeeper:
      HAS-ZK-APP:
       path: /zk-service/has-zk-app
       loadBalancerType: ROUND_ROBIN
       contentTypeTemplate: application/vnd.newsletter.$version+json
       version: v1
       #headers:
        # header1:
        #    - value1
        #  header2:
        #     - value2
       required: true
      # stubs: org.springframework:foo:stubs
      discovery:
        root: /zk-service
logging:
  level:
    org.springframework: error