server:
  port: 8087
spring:
  application:
    name: zookeeper-self
  cloud:
    zookeeper:
     discovery:
         root: /zk-service #这里指定后  下面的dependencies 的path在实际寻找的时候 就变为 /zk-service/zk-service/has-zk-app
     dependencies:
      has-zk-app1:
        path: /has-zk-app
        loadBalancerType: ROUND_ROBIN
        contentTypeTemplate: application/vnd.newsletter.$version+json
        version: v1
       #headers:
        # header1:
        #    - value1
        #  header2:
        #     - value2
        required: true
      # stubs: org.springframework:foo:stubs
     
logging:
  level:
    org.springframework: error